spring.application.name=trabalho-api

server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/trabalho_api
spring.datasource.username=postgres
spring.datasource.password=!@#$%

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true